repos:
- repo: git://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
    - id: go-fmt
    #- id: go-vet
    - id: go-cyclo
      args: [-over=150]
      #args: [-over=15]
    #- id: go-critic
    - id: go-unit-tests
    - id: go-mod-tidy
