ALTER TABLE blocks DROP INDEX idx_blocks_chain_id_period;

ALTER TABLE global_shares DROP INDEX idx_global_shares_chain_id_period;
ALTER TABLE global_shares DROP INDEX idx_global_shares_end_time_chain_id_period;

ALTER TABLE miner_shares DROP INDEX idx_miner_shares_miner_id_period;
ALTER TABLE miner_shares DROP INDEX idx_miner_shares_end_time_miner_id_chain_id_period;

ALTER TABLE worker_shares DROP INDEX idx_worker_shares_worker_id_period;
ALTER TABLE worker_shares DROP INDEX idx_worker_shares_end_time_worker_id_chain_id_period;
